### ISSUE TITLE
i tried to make it work but it wont

### ISSUE THREAD

**Issue by Phinwing** [Outer-Wilds-New-Horizons/nh-qsb-compatibility#1]
i put the file in the mod manager, took the dlls and put them in their respective areas, but there's no NHQSBCompat.dll that i can download
how do i find this dll

**Comment by xen-42** [comment]
yeah it doesn't work currently I don't think.  but the dll is here: https://github.com/Outer-Wilds-New-Horizons/nh-qsb-compatibility/suites/12844394712/artifacts/692165888

**Comment by ghost** [comment]
Trying to download the file gave me a "Failed to generate URL to download artifact" error. Is the link still working?

**Comment by xen-42** [comment]
Nah link is dead and im sure the mod wouldn't work anymore anyway, we basically all gave up on getting this to work. QSB changed a bunch of stuff somewhere along the way and now doesn't work with NH at all
